/*
 * SPDX-FileCopyrightText: 2025 The HedgeDoc developers (see AUTHORS file)
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { createParamDecorator, ExecutionContext } from '@nestjs/common';
import { Request } from 'express';
import { validate as uuidValidate } from 'uuid';

/**
 * Header name for the guest session UUID.
 * This UUID is generated by the frontend and stored in localStorage.
 * It allows guests to edit/delete their own comments.
 */
export const GUEST_SESSION_HEADER = 'x-guest-session';

/**
 * Extracts the guest session UUID from the request header.
 *
 * The guest session is a client-generated UUID that identifies a guest user's
 * browser session. This allows guests to edit and delete their own comments
 * even without logging in.
 *
 * @returns The guest session UUID if present and valid, otherwise null
 */
// oxlint-disable-next-line @typescript-eslint/naming-convention
export const RequestGuestSession = createParamDecorator(
  (_data: unknown, ctx: ExecutionContext): string | null => {
    const request: Request = ctx.switchToHttp().getRequest();
    const guestSession = request.headers[GUEST_SESSION_HEADER];

    if (typeof guestSession !== 'string') {
      return null;
    }

    // Validate that it's a proper UUID
    if (!uuidValidate(guestSession)) {
      return null;
    }

    return guestSession;
  },
);
